complete rewrite: use state explorer to determine current state, more robust implementation for adding, changing, removing key/values
Signed-off-by: Steven Armstrong <steven@icarus.ethz.ch>

diff --git a/conf/type/__key_value/manifest b/conf/type/__key_value/manifest
--- a/conf/type/__key_value/manifest
+++ b/conf/type/__key_value/manifest
@@ -19,5 +19,12 @@
 #
 
 # set defaults
-[ -f "$__object/parameter/key" ] \
-   || echo "$__object_id" > "$__object/parameter/key"
+key="$(cat "$__object/parameter/key" 2>/dev/null \
+   || echo "$__object_id" | tee "$__object/parameter/key")"
+state="$(cat "$__object/parameter/state" 2>/dev/null \
+   || echo "present" | tee "$__object/parameter/state")"
+
+if [ "$state" = "present" -a ! -f "$__object/parameter/value" ]; then
+   echo "Missing required parameter 'value'" >&2
+   exit 1
+fi 
