added support for non-stack hosts (just put them in the groups file somewhere)

diff --git a/local/cdist_wrapper b/local/cdist_wrapper
--- a/local/cdist_wrapper
+++ b/local/cdist_wrapper
@@ -35,19 +35,25 @@ if [ -z "$SYSTEMS" ]; then
 fi
 
 if [ -z "$SYSTEMS" ]; then
-  echo "ERROR: no systems passed, please choose from:"
-  echo
-  $DH --allsystems
+  echo "ERROR: no systems passed.  I know about these:"
+  stacksys=$($DH --allsystems)
+  groupsys=$(${__local}/lib/getGroups.pl --listall)
+  echo $stacksys $groupsys | sed -e 's/ /\n/g' | sort -u
   exit 2
 fi
 
 for s in $SYSTEMS; do
   $DH --sysinfo=$s > /dev/null
   if [ $? -ne 0 ]; then
-    echo "ERROR: $s is not a recognized system, please choose from:"
-    echo
-    $DH --allsystems
-    exit 2
+    # it's not in any stacks, maybe it's independent and just in groups?
+    ${__local}/lib/getGroups.pl $s > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "ERROR: $s is not a recognized system.  I know about these:"
+      stacksys=$($DH --allsystems)
+      groupsys=$(${__local}/lib/getGroups.pl --listall)
+      echo $stacksys $groupsys | sed -e 's/ /\n/g' | sort -u
+      exit 2
+    fi
   fi
 done
 
