Add pre-exists state to __file
This allows checking whether a file exists, but erroring out instead of
creating the file if it does not (or is not a regular file).

diff --git a/cdist/conf/type/__file/gencode-local b/cdist/conf/type/__file/gencode-local
--- a/cdist/conf/type/__file/gencode-local
+++ b/cdist/conf/type/__file/gencode-local
@@ -25,6 +25,20 @@ type="$(cat "$__object/explorer/type")"
 
 [ "$state_should" = "exists" -a "$type" = "file" ] && exit 0 # nothing to do
 
+if [ "$state_should" = "pre-exists" ]; then
+   if [ -f "$__object/parameter/source" ]; then
+      echo "--source cannot be used with --state pre-exists"
+      exit 1
+   fi
+
+   if [ "$type" = "file" ]; then
+      exit 0 # nothing to do
+   else
+      echo "File \"$destination\" does not exist"
+      exit 1
+   fi
+fi
+
 upload_file=
 create_file=
 if [ "$state_should" = "present" -o "$state_should" = "exists" ]; then
