prefix error messages with Error:
Signed-off-by: Steven Armstrong <steven@icarus.ethz.ch>

diff --git a/bin/cdist-config b/bin/cdist-config
--- a/bin/cdist-config
+++ b/bin/cdist-config
@@ -160,7 +160,7 @@ __cdist_exec_fail_on_error()
 
 __cdist_exit_err()
 {
-   echo "$@" >&2
+   echo "Error: $@" >&2
    exit 1
 }
 
