first version of __dog_vdi
Signed-off-by: Nico Schottelius <nico@bento.schottelius.org>

diff --git a/cdist/conf/type/__dog_vdi/manifest b/cdist/conf/type/__dog_vdi/manifest
--- a/cdist/conf/type/__dog_vdi/manifest
+++ b/cdist/conf/type/__dog_vdi/manifest
@@ -19,24 +19,10 @@
 #
 
 state_should="$(cat "$__object/parameter/state")"
-num_vdi_lines=$(wc -l < "$__object/explorer/list")
-name="$__object_id"
 
-
-if [ "$num_vdi_lines" = 1 ]; then
-    state_is=present
-else
-    state_is=absent
+if [ "$state_should" = "present" ]; then
+    if [ ! -f "$__object/parameter/size" ]; then
+        echo "Size is required when state is present" >&2
+        exit 1
+    fi
 fi
-
-[ "$state_is" = "$state_should" ] && exit 0
-
-case "$state_should" in
-    present)
-        size="$(cat "$__object/parameter/size")"
-        echo "dog vdi create '$name' '$size'"
-    ;;
-    absent)
-        echo "dog vdi delete '$name'"
-    ;;
-esac
