catch unsupported state cases in __dog_vdi und __qemu_img
Signed-off-by: Nico Schottelius <nico@bento.schottelius.org>

diff --git a/cdist/conf/type/__dog_vdi/manifest b/cdist/conf/type/__dog_vdi/manifest
--- a/cdist/conf/type/__dog_vdi/manifest
+++ b/cdist/conf/type/__dog_vdi/manifest
@@ -20,9 +20,17 @@
 
 state_should="$(cat "$__object/parameter/state")"
 
-if [ "$state_should" = "present" ]; then
-    if [ ! -f "$__object/parameter/size" ]; then
-        echo "Size is required when state is present" >&2
+case "$state_should" in
+    present)
+        if [ ! -f "$__object/parameter/size" ]; then
+            echo "Size is required when state is present" >&2
+            exit 1
+        fi
+    absent)
+        :
+    ;;
+    *)
+        echo "Unsupported state: $state_should" >&2
         exit 1
-    fi
-fi
+    ;;  
+esac
