Fix checking for target dir.

diff --git a/cdist/conf/type/__preos_debian/gencode-local b/cdist/conf/type/__preos_debian/gencode-local
--- a/cdist/conf/type/__preos_debian/gencode-local
+++ b/cdist/conf/type/__preos_debian/gencode-local
@@ -24,19 +24,19 @@ then
     exit 1
 fi
 
-target_dir="/$__object_id"
-if [ -e "$target_dir" ]
-then
-    echo "ERROR: "$target_dir" already exists " >&2
-    exit 1
-fi
-
 arch=$(cat "$__object/parameter/arch")
 suite=$(cat "$__object/parameter/suite")
 
 # bootstrap
 if [ -f "$__object/parameter/bootstrap" ]
 then
+    target_dir="/$__object_id"
+    if [ -e "$target_dir" ]
+    then
+        echo "ERROR: "${target_dir}" already exists " >&2
+        exit 1
+    fi
+
     cat <<EOF
 mkdir -p "${target_dir}"
 debootstrap --include=openssh-server --arch="${arch}" "${suite}" "${target_dir}"
