manifest bug

diff --git a/conf/type/__apache_vhost/manifest b/conf/type/__apache_vhost/manifest
--- a/conf/type/__apache_vhost/manifest
+++ b/conf/type/__apache_vhost/manifest
@@ -23,8 +23,8 @@
 # set documentroot value
 # function to prepare variables regarding parameters
 # takes variable's name, parameter's name and default value
+#set -x
 prepare() {
-set -x
 if [ ! "$3" ]; then
   echo "We need a default value"
   exit 1
@@ -35,7 +35,6 @@ if [ -f "$__object/parameter/$2" ]; then
 else
   eval $1=$3
 fi
-set +x
 }
 
 prepare "root" "root" "/var/www/$__object_id"
@@ -43,27 +42,28 @@ prepare "servername" "servername" "$__object_id"
 prepare "location" "location" "/"
 prepare "index" "index" "index.php"
 prepare	"state"	"state"	"disabled"
+echo "State is finished"
 
 if [ -f "$__object/parameter/template" ] && [ -f "$__object/parameter/source" ]; then
   echo "Please use either a source or a template"
   exit 1;
 fi
 #FIXME: need to find a place for full configurations
-if [ -f "$__object/parameter/template" ]; then
+echo "FIXME"
 	prepare "tpl" "template" "$__type/files/basic.tpl"
 	if [ ! -f "$tpl" ]; then
 	  echo "Missing template $tpl"
 	  exit 1
 	fi
-fi
+echo "Template"
 
-if  [ -f "$__object/parameter/source" ]; then
-        prepare "tpl" "template" "$__type/files/basic.vhost"
-        if [ ! -f "$tpl" ]; then
-          echo "Missing template $tpl"
-          exit 1
-        fi
-fi
+#if  [ -f "$__object/parameter/source" ]; then
+#        prepare "tpl" "template" "$__type/files/basic.vhost"
+#        if [ ! -f "$tpl" ]; then
+#          echo "Missing template $tpl"
+#          exit 1
+#        fi
+#fi
 
 
 
@@ -84,15 +84,14 @@ sed -i "s!\$REPO!$repo!g" $tmpconf
 echo "}" >> $tmpconf
 
 # send the file
+os=$(cat "$__global/explorer/os")
+echo "$os"
 case "$os" in
 	fedora|centos|redhat)
 		a2package="httpd"
 		__addifnosuchline sites --file /etc/$a2package/httpd.conf --line "Include /etc/$a2package/sites-enabled/*.conf"
 	;;
-	archlinux)
-		a2package="apache2"
-	;;
-	debian)
+	archlinux|ubuntu|debian)
 		a2package="apache2"
 	;;
 	*)
