added --source option to apache_vhost type

diff --git a/conf/type/__apache_vhost/manifest b/conf/type/__apache_vhost/manifest
--- a/conf/type/__apache_vhost/manifest
+++ b/conf/type/__apache_vhost/manifest
@@ -57,13 +57,13 @@ echo "FIXME"
 	fi
 echo "Template"
 
-#if  [ -f "$__object/parameter/source" ]; then
-#        prepare "tpl" "template" "$__type/files/basic.vhost"
-#        if [ ! -f "$tpl" ]; then
-#          echo "Missing template $tpl"
-#          exit 1
-#        fi
-#fi
+if  [ -f "$__object/parameter/source" ]; then
+        prepare "tpl" "source" "$__type/files/basic.vhost"
+        if [ ! -f "$tpl" ]; then
+          echo "Missing template $tpl"
+          exit 1
+        fi
+fi
 
 
 
