Update __docker type
  - Update installation method, following official installation
instructions.
  - docker-engine was renamed to Docker CE around March 2017. Update
manpage to reflect that change.
  - Remove flag `--experimental` since it is no longer necessary to install a
different binary to get experimental features. Experimental features are
included in the stable binary and can be enabled by a flag or in a
config file.

diff --git a/cdist/conf/type/__docker/manifest b/cdist/conf/type/__docker/manifest
--- a/cdist/conf/type/__docker/manifest
+++ b/cdist/conf/type/__docker/manifest
@@ -24,56 +24,36 @@ state=$(cat "$__object/parameter/state")
 
 case "$os" in
     centos)
-        component="main"
-        if [ -f "$__object/parameter/experimental" ]; then
-          component="experimental"
+        if (source "$__global/explorer/os_release" && [ "${VERSION_ID}" = "7" ]); then
+          __yum_repo docker-ce-stable \
+            --name 'Docker CE Stable' \
+            --baseurl "https://download.docker.com/linux/centos/7/\$basearch/stable" \
+            --enabled \
+            --gpgcheck 1 \
+            --gpgkey 'https://download.docker.com/linux/centos/gpg' \
+            --state ${state}
+          require="__yum_repo/docker-ce-stable" __package docker-ce --state ${state}
+        else
+          echo "CentOS version 7 is required!" >&2
+          exit 1
         fi
-        __yum_repo docker \
-          --name 'Docker Repository' \
-          --baseurl "https://yum.dockerproject.org/repo/$component/centos/\$releasever/" \
-          --enabled \
-          --gpgcheck 1 \
-          --gpgkey 'https://yum.dockerproject.org/gpg' \
-          --state ${state} 
-        require="__yum_repo/docker" __package docker-engine --state ${state}
     ;;
-    ubuntu)
-        component="main"
-      if [ -f "$__object/parameter/experimental" ]; then
-         component="experimental"
+    ubuntu|debian)
+      if [ "${state}" = "present" ]; then
+        __package apt-transport-https
+        __package ca-certificates
+        __package gnupg2
       fi
-      __package apparmor --state ${state}
-      __package ca-certificates --state ${state}
-      __package apt-transport-https --state ${state}
-      __apt_key docker --keyid 58118E89F3A912897C070ADBF76221572C52609D --state ${state}
+      __apt_key_uri docker --name "Docker Release (CE deb) <docker@docker.com>" \
+        --uri "https://download.docker.com/linux/${os}/gpg" --state ${state}
       export CDIST_ORDER_DEPENDENCY=on
       __apt_source docker \
-         --uri https://apt.dockerproject.org/repo \
-         --distribution "ubuntu-$(cat "$__global/explorer/lsb_codename")" \
+         --uri "https://download.docker.com/linux/${os}" \
+         --distribution "$(cat "$__global/explorer/lsb_codename")" \
          --state ${state} \
-         --component "$component"
-      __package docker-engine --state ${state}
+         --component "stable"
+      __package docker-ce --state ${state}
       unset CDIST_ORDER_DEPENDENCY
-   ;;
-   debian)
-       component="main"
-      if [ -f "$__object/parameter/experimental" ]; then
-         component="experimental"
-      fi
-
-      __package apt-transport-https --state ${state}
-      __package ca-certificates --state ${state}
-      __package gnupg2 --state ${state}
-      __apt_key docker --keyid 58118E89F3A912897C070ADBF76221572C52609D --state ${state}
-      export CDIST_ORDER_DEPENDENCY=on
-      __apt_source docker \
-          --uri https://apt.dockerproject.org/repo \
-          --distribution "debian-$(cat "$__global/explorer/lsb_codename")" \
-          --state ${state} \
-          --component "$component"
-      __package docker-engine --state ${state}
-      unset CDIST_ORDER_DEPENDENCY
-
    ;;
    *)
       echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
