Added singleton, fixed remote side test logic
Fixed logic to perform tests on remote side including communicating with
cdist server (by way of having cdist place a canary file on remote side)

diff --git a/conf/type/__pf/gencode-remote b/conf/type/__pf/gencode-remote
--- a/conf/type/__pf/gencode-remote
+++ b/conf/type/__pf/gencode-remote
@@ -39,44 +39,61 @@ rcvar="$(cat "$__object/explorer/rcvar")"
 cksum="$(cat "$__object/explorer/cksum")"
 
 cat <<EOF
-exec >&2
-set -x
 # This file is used as a canary later, make sure we don't get a false positive
-rm -f /tmp/test
+if [ -f /tmp/pf_test.$__target_host ]; then
+	rm -f /tmp/pf_test.$__target_host
+fi
+
+currentstate="\$(pfctl -si 2>&1 | grep Status: | sed 's/^Status: \(.*\) for.*$/\1/g')"
 
 if [ "$state" = "enabled" ]; then
-	pfctl -e || true
+	if [ ! "\$currentstate" = "Enabled" ]; then
+		pfctl -e 2>&1 >&-
+	fi
 else
-	pfctl -d || true
-	exit 0
+	if [ ! "\$currentstate" = "Disabled" ]; then
+		pfctl -d 2>&1 >&-
+		exit 0
+	fi
 fi
 
 revert() {
-	pfctl -f "${rcvar}"
+	pfctl -f "${rcvar}" 2>&1 >&-
 	echo "Test(s) failed after applying new ruleset." >&2
 	echo "Reverting back to previous ruleset." >&2
 	exit 255
 }
 
 if [ -f "${rcvar}.new" ]; then
-	pfctl -f "${rcvar}.new"
+	pfctl -f "${rcvar}.new" 2>&1 >&-
+	pfstatus="\$?"
 fi
 if [ -f "${rcvar}.tests" ]; then
 	sh ${rcvar}.tests
+	teststatus="\$?"
 fi
-if [ ! "\$?" -eq "0" ]; then	# error occurred
+
+if [ -z "\$teststatus" ]; then	# no tests executed
+elif [ ! "\$teststatus" -eq "0" ]; then	# tests failed
 	revert
-else	# test(s) succeeded
-	sleep 20
-	if [ ! -f /tmp/test ]; then	# Apparently the upstream cdist server can't get back to us
+fi
+if [ -z "\$pfstatus" ]; then	# pfctl wasn't called -- ruleset unchanged
+	exit 0
+elif [ ! "\$pfstatus" -eq "0" ]; then	# pfctl call failed
+	revert
+else	# pfctl call succeeded
+	sleep 10
+	if [ ! -f /tmp/pf_test.$__target_host ]; then	# Apparently the upstream cdist server can't get back to us
 		revert
 	else
-		rm -f "${rcvar}" "${rcvar}.tests"
-		mv "${rcvar}.new" "${rcvar}"
-		exit 0
+		if [ -f "${rcvar}.tests" ]; then
+			rm -f "${rcvar}" "${rcvar}.tests"
+		fi
+		if [ -f "${rcvar}.new" ]; then
+			mv "${rcvar}.new" "${rcvar}"
+		fi
 	fi
 fi
-set +x
 EOF
 
 # Debug
