[type/__user] Make shellcheck happy

diff --git a/cdist/conf/type/__user/explorer/shadow b/cdist/conf/type/__user/explorer/shadow
--- a/cdist/conf/type/__user/explorer/shadow
+++ b/cdist/conf/type/__user/explorer/shadow
@@ -38,9 +38,10 @@ esac
 
 if command -v getent >/dev/null 2>&1
 then
+  # shellcheck disable=SC2015
   getent "${database}" "${name}" 2>/dev/null && exit || true  # fallback to file
 fi
 if test -n "${database}" -a -f "/etc/${database}"
 then
-  grep -e "^${name}:" "/etc/${database}" && exit || true  # ignore failure
+  grep -e "^${name}:" "/etc/${database}" || true  # ignore failure
 fi
