Clean quotes; su - -> su -l

diff --git a/cdist/conf/type/__package_pkg_freebsd/gencode-remote b/cdist/conf/type/__package_pkg_freebsd/gencode-remote
--- a/cdist/conf/type/__package_pkg_freebsd/gencode-remote
+++ b/cdist/conf/type/__package_pkg_freebsd/gencode-remote
@@ -27,8 +27,8 @@ assert ()                 #  If condition false,
 
 	if [ ! "$1" ] 
 	then
-		echo "Assertion failed:  \"$1\""
-		echo "File \"$0\""
+		echo "Assertion failed:  '$1'"
+		echo "File '$0'"
 		exit $E_ASSERT_FAILED
 	fi  
 }
@@ -64,12 +64,14 @@ execcmd(){
 		[ -n "$version" ] && pkgsite="${pkgsite}/All/" || pkgsite="${pkgsite}/Latest/"
 		echo "${pkgsite}"
 	fi
-	echo "${2} 2>&- >&-"	# Silence the output of the command
-	echo "status=\$?"
-	echo "if [ \"\$status\" -ne \"0\" ]; then"
-	echo "	echo \"Error: ${cmd} exited nonzero with \$status\"'!' >&2"
-	echo "	exit 1"
-	echo "fi"
+    cat <<EOF
+${2} 2>&- >&-  # Silence the output of the command
+status=\$?
+if [ "\$status" -ne "0" ]; then
+	echo "Error: ${cmd} exited nonzero with \$status!" >&2
+	exit 1
+fi
+EOF
 }
 
 if [ -n "$curr_version" ]; then	# PKG *is* installed
diff --git a/cdist/conf/type/__ssh_authorized_key/gencode-remote b/cdist/conf/type/__ssh_authorized_key/gencode-remote
--- a/cdist/conf/type/__ssh_authorized_key/gencode-remote
+++ b/cdist/conf/type/__ssh_authorized_key/gencode-remote
@@ -25,7 +25,7 @@ the_key="$(cat "$__object/parameter/key")"
 validated_key="$(echo "${the_key}" | tr ' ' '\n' | awk '/^(ssh|ecdsa)-[^ ]+/ { printf $1" "; getline; printf $1 }')"
 if [ -z "${validated_key}" ]
 then
-    echo "Key is invalid: \"${the_key}\"" >&2
+    echo "Key is invalid: '${the_key}'" >&2
     exit 1
 fi
 
