Clean quotes; su - -> su -l

diff --git a/cdist/conf/type/__line/gencode-remote b/cdist/conf/type/__line/gencode-remote
--- a/cdist/conf/type/__line/gencode-remote
+++ b/cdist/conf/type/__line/gencode-remote
@@ -35,7 +35,7 @@ state_is="$(cat "$__object/explorer/state")"
 case "$state_should" in
     present)
         if [ ! "$line" ]; then
-            echo "Required parameter \"line\" is missing" >&2
+            echo "Required parameter 'line' is missing" >&2
             exit 1
         fi
 
diff --git a/cdist/conf/type/__package_pkgng_freebsd/gencode-remote b/cdist/conf/type/__package_pkgng_freebsd/gencode-remote
--- a/cdist/conf/type/__package_pkgng_freebsd/gencode-remote
+++ b/cdist/conf/type/__package_pkgng_freebsd/gencode-remote
@@ -70,12 +70,14 @@ execcmd(){
          ;;
    esac
 
-   echo "$_cmd 2>&- >&-"   # Silence the output of the command
-   echo "status=\$?"
-   echo "if [ \"\$status\" -ne \"0\" ]; then"
-   echo "	echo \"Error: ${_cmd} exited nonzero with \$status\"'!' >&2"
-   echo "	exit 1"
-   echo "fi"
+   cat <<EOF
+$_cmd 2>&- >&-  # Silence the output of the command
+status=\$?
+if [ "\$status" -ne "0" ]; then
+	echo "Error: ${_cmd} exited nonzero with \$status!" >&2
+	exit 1
+fi
+EOF
 }
 
 if [ -n "$curr_version" ]; then  # PKG *is* installed
