__daemontools*: add/improve; + add man pages

diff --git a/cdist/conf/type/__daemontools_service/manifest b/cdist/conf/type/__daemontools_service/manifest
--- a/cdist/conf/type/__daemontools_service/manifest
+++ b/cdist/conf/type/__daemontools_service/manifest
@@ -10,6 +10,13 @@ run=$(cat "$__object/parameter/run")
 runfile=$(cat "$__object/parameter/run-file")
 logrun=$(cat "$__object/parameter/log-run")
 
+svc=$(cat "$__type/explorer/svc")
+
+if [ -z "$svc" ]; then
+	echo "svc not found! Install daemontools first: see __daemontools"
+	exit 1
+fi
+
 badusage() {
 	echo "__daemontools_service/$__object_id: exactly one of --run, --run-file must be set" >&2
 	exit 1
