Add support for FreeBSD 10.x jails
Separate __jail type into distinct __jail_freebsd9 and __jail_freebsd10 types

diff --git a/cdist/conf/type/__jail_freebsd10/gencode-local b/cdist/conf/type/__jail_freebsd10/gencode-local
--- a/cdist/conf/type/__jail_freebsd10/gencode-local
+++ b/cdist/conf/type/__jail_freebsd10/gencode-local
@@ -23,33 +23,30 @@
 #
 
 # Debug
-#exec >&2
-#set -x
-
-# Can only be used on FreeBSD
-os="$(cat "$__global/explorer/os")"
-if [ ! "$os" = "freebsd" ]; then
-   echo "__jail can only be used on FreeBSD targets!" >&2
-   exit 1
-fi
+exec >&2
+set -x
 
 jaildir="$(cat "$__object/parameter/jaildir")"
 
-__directory ${jaildir} --parents
+jailbase="$(cat "$__object/parameter/jailbase")"
 
-set -- "$@" "$__object_id" "--state" "$state"
-cd "$__object/parameter"
-for property in $(ls .); do
-	set -- "$@" "--$property" "$(cat "$property")"
-done
+state="$(cat "$__object/parameter/state")"
 
-ver="$(cat "$__global/explorer/os_version")"
-if [ -n "$(echo "$ver" | grep '^10\.' )" ]; then   # Version is 10.x
-   __jail_freebsd10 "$@"
-else
-   __jail_freebsd9 "$@"
+if [ "$state" = "present" ] && [ -z "$jailbase" ]; then
+   exec >&2
+   echo "jailbase is a REQUIRED parameter when state=present!"
+   exit 1
 fi
 
+remotebase="${jaildir}/jailbase.tgz"
+basepresent="$(cat "$__object/explorer/basepresent")"
+
+if [ "$state" = "present" ]; then
+   if [ "$basepresent" = "NONE" ]; then
+      echo "$__remote_copy" "${jailbase}" "$__target_host:${remotebase}"
+   fi   # basepresent=NONE
+fi   # state=present
+
 # Debug
-#set +x
+set +x
 
