Code cleanup
Modified formatting (s/<TAB>/   /g)
Changed parm from running/stopped to present/absent

diff --git a/conf/type/__service/gencode-remote b/conf/type/__service/gencode-remote
--- a/conf/type/__service/gencode-remote
+++ b/conf/type/__service/gencode-remote
@@ -23,7 +23,7 @@
 #exec >&2
 #set -x
 
-state="$(cat "$__object/parameter/status")"
+state="$(cat "$__object/parameter/state")"
 
 ### Begin forming $cmd
 cmd=""
@@ -31,24 +31,24 @@ cmd="$(cat <<EOF
 name="$__object_id"
 
 # Stupid Bourne shell and its lack of array support...
-rc_dirs="$(echo /etc/rc.d:/usr/local/etc/rc.d)"
+rc_dirs="/etc/rc.d:/usr/local/etc/rc.d"
 exists=""
 save_IFS="\$IFS"
 IFS=":"
 for dir in \$rc_dirs; do
-	[ -f "\$dir/\$name" ] && exists="\$dir/\$name"
+   [ -f "\$dir/\$name" ] && exists="\$dir/\$name"
 done
 IFS="\$save_IFS"
 
 if [ -z "\$exists" ]; then
-	echo "\$name doesn't exist as a system service on \$__target_host." >&2
-	exit -1
+   echo "\$name doesn't exist as a system service on \$__target_host." >&2
+   exit -1
 fi
 
 status="\$("\$exists" status || true)"
 if [ "\$(expr "\$status" : "Cannot 'status' \$name. Set \${name}_enable to YES")" != "0" ]; then
-	echo "Can't status \$name. Set \${name}_enable to YES first in rc.conf on \$__target_host." >&2
-	exit -1
+   echo "Can't status \$name. Set \${name}_enable to YES first in rc.conf on \$__target_host." >&2
+   exit -1
 fi
 
 EOF)"
@@ -57,38 +57,38 @@ EOF)"
 ### Begin forming $running
 running="$(cat <<EOF
 if [ \$(expr "\$status" : ".*stopped.*") != "0" ]; then
-	"\$exists" start 2>&- >&-
+   "\$exists" start 2>&- >&-
 elif [ \$(expr "\$status" : ".*not running.*") != "0" ]; then
-	"\$exists" start 2>&- >&-
+   "\$exists" start 2>&- >&-
 elif [ \$(expr "\$status" : ".*dead.*") != "0" ]; then
-	"\$exists" restart 2>&- >&-
+   "\$exists" restart 2>&- >&-
 fi
 EOF)"
 ### End forming $running
 
 ### Begin forming $stopped
 stopped="$(cat <<EOF
-if [ \$(expr "\$status" : ".*not running.*") != "0" ]; then
-          # Do nothing -- expr cannot handle negative fwd lookups
-          #    (to my knowledge, anyway)
-         echo
-      elif [ \$(expr "\$status" : ".*running.*") != "0" ]; then
-         "\$exists" stop 2>&- >&-
-      fi
+   if [ \$(expr "\$status" : ".*not running.*") != "0" ]; then
+      # Do nothing -- expr cannot handle negative fwd lookups
+      #    (to my knowledge, anyway)
+      echo
+   elif [ \$(expr "\$status" : ".*running.*") != "0" ]; then
+      "\$exists" stop 2>&- >&-
+   fi
 EOF)"
 ### End forming $stopped
 
 case "$state" in
-	running)
-		cmd="$(echo "${cmd}\n${running}")"
-		;;
-	stopped)
-		cmd="$(echo "${cmd}\n${stopped}")"
-		;;
-	*)
-		echo "Unknown state: ${state}" >&2
-		exit 1
-		;;
+   present)
+      cmd="$(echo "${cmd}\n${running}")"
+      ;;
+   absent)
+      cmd="$(echo "${cmd}\n${stopped}")"
+      ;;
+   *)
+      echo "Unknown state: ${state}" >&2
+      exit 1
+      ;;
 esac
 
 echo "${cmd}"
