Support pacman with --maxage parameter

diff --git a/cdist/conf/type/__package_update_index/gencode-remote b/cdist/conf/type/__package_update_index/gencode-remote
--- a/cdist/conf/type/__package_update_index/gencode-remote
+++ b/cdist/conf/type/__package_update_index/gencode-remote
@@ -22,32 +22,33 @@
 #
 
 type=$(cat "$__object/explorer/type")
+currage="$(cat "$__object/explorer/currage")"
 if [ -f "$__object/parameter/maxage" ]; then
     maxage="$(cat "$__object/parameter/maxage")"
-    currage="$(cat "$__object/explorer/currage")"
 fi
 
-if [ -n "$maxage" ] && [ "$type" != "apt" ]; then
-    echo "ERROR: \"--maxage\" only supported for \"apt\" pkg-manager." >&2
-    exit 1
+if [ -n "$maxage" ]; then
+    if [ "$type" != "apt" -a "$type" != "pacman" ]; then
+        echo "ERROR: \"--maxage\" only supported for \"apt\" or \"pacman\" pkg-manager." >&2
+        exit 1
+    elif [ $currage -lt $maxage ]; then
+        exit 0 # no need to update
+    fi
 fi
+
 
 case "$type" in
     yum) ;;
-    apt) if [ -n "$maxage" ]; then
-             ## check if we need to update:
-             if [ $currage -ge $maxage ]; then
-                echo "apt-get --quiet update"
-                echo "apt-cache updated (age was: $currage)" >> "$__messages_out"
-             fi
-         else
-                echo "apt-get --quiet update"
-                echo "apt-cache updated (age was: $currage)" >> "$__messages_out"
-         fi
-         ;;
-    pacman) echo "pacman --noprogressbar --sync --refresh" ;;
+    apt)
+        echo "apt-get --quiet update"
+        echo "apt-cache updated (age was: $currage)" >> "$__messages_out"
+        ;;
+    pacman)
+        echo "pacman --noprogressbar --sync --refresh"
+        echo "pacman package database synced (age was: $currage)" >> "$__messages_out"
+        ;;
     *)
-        echo "Don't know how to manage packages on: $os" >&2
+        echo "Don't know how to manage packages for type: $type" >&2
         exit 1
         ;;
 esac
